version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    command: sh -c "/wait && /opt/cubicasa/cubicasa"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cubicasa
      POSTGRES_PASSWORD: password
